schema_version: 1
app:
  log_level: info
  metrics_addr: ":9090"

routes:
  - from: rabbit
    to: [kafka, nats]
    direction: both
    filters:
      - type: drop
        topics: ["telemetry.*"]
      - type: minimum
        topics: ["metric.*"]
        window: "5s"
    qos:
      acks: at_least_once
      max_inflight: 1000
    ttl:
      timeout: "30s"
      max_hops: 3

rabbit:
  url: "amqps://user:pass@host/vhost"
  tls:
    enabled: true
    insecure_skip_verify: true


kafka:
  brokers: ["k1:9093","k2:9093"]
  tls:
    enabled: false

nats:
  url: "nats://n1:4222"
  tls:
    enabled: false

persistence:
  type: badger
  path: "./data"

protobuf:
  files: ["./proto/msg.proto"]
  msg_type: "telemetry.Message"

compression: none
